// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PinealWebMvc.Data;

namespace PinealWebMvc.Migrations
{
    [DbContext(typeof(PinealWebMvcContext))]
    partial class PinealWebMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PinealWebMvc.Models.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Imagem");
                });

            modelBuilder.Entity("PinealWebMvc.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("TipoId")
                        .HasColumnType("int");

                    b.Property<int>("VertenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.HasIndex("VertenteId");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("PinealWebMvc.Models.Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("PinealWebMvc.Models.Track", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("double");

                    b.Property<DateTime>("Lançamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("int");

                    b.Property<int>("TrackProperty")
                        .HasColumnType("int");

                    b.Property<int?>("VertenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("VertenteId");

                    b.ToTable("Track");
                });

            modelBuilder.Entity("PinealWebMvc.Models.Vertente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Vertente");
                });

            modelBuilder.Entity("PinealWebMvc.Models.Imagem", b =>
                {
                    b.HasOne("PinealWebMvc.Models.Projeto", null)
                        .WithMany("Imagens")
                        .HasForeignKey("ProjetoId");
                });

            modelBuilder.Entity("PinealWebMvc.Models.Projeto", b =>
                {
                    b.HasOne("PinealWebMvc.Models.Tipo", "Tipo")
                        .WithMany("Projetos")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PinealWebMvc.Models.Vertente", "Vertente")
                        .WithMany("Projetos")
                        .HasForeignKey("VertenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PinealWebMvc.Models.Track", b =>
                {
                    b.HasOne("PinealWebMvc.Models.Projeto", "Projeto")
                        .WithMany("Tracks")
                        .HasForeignKey("ProjetoId");

                    b.HasOne("PinealWebMvc.Models.Vertente", "Vertente")
                        .WithMany()
                        .HasForeignKey("VertenteId");
                });
#pragma warning restore 612, 618
        }
    }
}
